Document: gpsbabel
Title: Debian gpsbabel Manual
Author: <insert document author here>
Abstract: This manual describes what gpsbabel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gpsbabel/gpsbabel.sgml.gz

Format: postscript
Files: /usr/share/doc/gpsbabel/gpsbabel.ps.gz

Format: text
Files: /usr/share/doc/gpsbabel/gpsbabel.text.gz

Format: HTML
Index: /usr/share/doc/gpsbabel/html/index.html
Files: /usr/share/doc/gpsbabel/html/*.html

  
