.TH GPSBABEL 1 "November 10, 2006" "gpsbabel 1.3.2"
.SH NAME
gpsbabel \- Universal gps format translator
.SH SYNOPSIS
.br
/usr/bin/gpsbabel [options] \-i INTYPE \-f INFILE \-o OUTTYPE \-F OUTFILE
.br
/usr/bin/gpsbabel [options] \-i INTYPE \-o OUTTYPE INFILE [OUTFILE]
.br
.SH DESCRIPTION

.br
Converts GPS route and waypoint data from one format type to another.
.br
The input type and filename are specified with the \-i INTYPE
.br
and \-f INFILE options. The output type and filename are specified
.br
with the \-o OUTTYPE and \-F OUTFILE options.
.br
If '-' is used for INFILE or OUTFILE, stdin or stdout will be used.
.br

.br
In the second form of the command, INFILE and OUTFILE are the
.br
first and second positional (non-option) arguments.
.br

.br
INTYPE and OUTTYPE must be one of the file types listed below, and
.br
may include options valid for that file type.  For example:
.br
\'gpx', 'gpx,snlen=10' and 'ozi,snlen=10,snwhite=1'
.br
(without the quotes) are all valid file type specifications.
.br

.SH OPTIONS
.br
\-p               Preferences file (gpsbabel.ini)
.br
\-s               Synthesize shortnames
.br
\-r               Process route information
.br
\-t               Process track information
.br
\-w               Process waypoint information [default]
.br
\-b               Process command file (batch mode)
.br
\-c               Character set for next operation
.br
\-N               No smart icons on output
.br
\-x filtername    Invoke filter (place between inputs and output) 
.br
\-D level         Set debug level [0]
.br
\-l               Print GPSBabel builtin character sets and exit
.br
\-h, -?           Print detailed help and exit
.br
\-V               Print GPSBabel version and exit
.br


.br
File Types (\-i and \-o options):
.br
	baroiq                Brauniger IQ Series Barograph Download
.br
	cambridge             Cambridge/Winpilot glider software
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	cst                   CarteSurTable data file
.br
	cetus                 Cetus for Palm/OS
.br
	  dbname                Database name 
.br
	  appendicon            (0/1) Append icon_descr to description 
.br
	coastexp              CoastalExplorer XML
.br
	csv                   Comma separated values
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	compegps              CompeGPS data files (.wpt/.trk/.rte)
.br
	  deficon               Default icon name 
.br
	  index                 Index of route/track to write (if more than one in source)
.br
	  radius                Give points (waypoints/route points) a default radius (proximity).
.br
	  snlen                 Length of generated shortnames (default 16) 
.br
	copilot               CoPilot Flight Planner for Palm/OS
.br
	coto                  cotoGPS for Palm/OS
.br
	  zerocat               Name of the 'unassigned' category 
.br
	axim_gpb              Dell Axim Navigation System (.gpb) file format
.br
	an1                   DeLorme .an1 (drawing) file
.br
	  type                  Type of .an1 file 
.br
	  road                  Road type changes 
.br
	  nogc                  (0/1) Do not add geocache data to description 
.br
	  deficon               Symbol to use for point data 
.br
	  color                 Color for lines or mapnotes 
.br
	  zoom                  Zoom level to reduce points 
.br
	  wpt_type              Waypoint type 
.br
	  radius                Radius for circles 
.br
	gpl                   DeLorme GPL
.br
	saplus                DeLorme Street Atlas Plus
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	saroute               DeLorme Street Atlas Route
.br
	  turns_important       (0/1) Keep turns if simplify filter is used 
.br
	  turns_only            (0/1) Only read turns; skip all other points 
.br
	  split                 (0/1) Split into multiple routes at turns 
.br
	  controls              Read control points as waypoint/route/none 
.br
	  times                 (0/1) Synthesize track times 
.br
	xmap                  DeLorme XMap HH Native .WPT
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	xmap2006              DeLorme XMap/SAHH 2006 Native .TXT
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	xmapwpt               DeLorme XMat HH Street Atlas USA .WPT (PPC)
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	easygps               EasyGPS binary format
.br
	igc                   FAI/IGC Flight Recorder Data Format
.br
	  timeadj               (integer sec or 'auto') Barograph to GPS time diff 
.br
	gpssim                Franson GPSGate Simulation
.br
	  wayptspd              Default speed for waypoints (knots/hr) 
.br
	  split                 (0/1) Split input into separate files 
.br
	fugawi                Fugawi
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	garmin301             Garmin 301 Custom position and heartrate
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	glogbook              Garmin Logbook XML
.br
	gdb                   Garmin MapSource \- gdb
.br
	  cat                   Default category on output (1..16) 
.br
	  ver                   Version of gdb file to generate (1,2) 
.br
	  via                   (0/1) Drop route points that do not have an equivalent w 
.br
	mapsource             Garmin MapSource \- mps
.br
	  snlen                 Length of generated shortnames 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  mpsverout             Version of mapsource file to generate (3,4,5) 
.br
	  mpsmergeout           (0/1) Merge output with existing file 
.br
	  mpsusedepth           (0/1) Use depth values on output (default is ignore) 
.br
	  mpsuseprox            (0/1) Use proximity values on output (default is ignore) 
.br
	garmin_txt            Garmin MapSource \- txt (tab delimited)
.br
	  date                  Read/Write date format (i.e. yyyy/mm/dd) 
.br
	  datum                 GPS datum (def. WGS 84) 
.br
	  dist                  Distance unit [m=metric, s=statute] 
.br
	  prec                  Precision of coordinates 
.br
	  temp                  Temperature unit [c=Celsius, f=Fahrenheit] 
.br
	  time                  Read/Write time format (i.e. HH:mm:ss xx) 
.br
	  utc                   Write timestamps with offset x to UTC time 
.br
	pcx                   Garmin PCX5
.br
	  deficon               Default icon name 
.br
	  cartoexploreur        (0/1) Write tracks compatible with Carto Exploreur 
.br
	garmin_poi            Garmin POI database
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	garmin                Garmin serial/USB protocol
.br
	  snlen                 Length of generated shortnames 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  deficon               Default icon name 
.br
	  get_posn              (0/1) Return current position as a waypoint 
.br
	  power_off             (0/1) Command unit to power itself down 
.br
	  category              Category number to use for written waypoints 
.br
	gtrnctr               Garmin Training Centerxml
.br
	geo                   Geocaching.com .loc
.br
	  deficon               Default icon name 
.br
	  nuke_placer           (0/1) Omit Placer name 
.br
	gcdb                  GeocachingDB for Palm/OS
.br
	geonet                GEOnet Names Server (GNS)
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	geoniche              GeoNiche .pdb
.br
	  dbname                Database name (filename) 
.br
	  category              Category name (Cache) 
.br
	kml                   Google Earth (Keyhole) Markup Language
.br
	  deficon               Default icon name 
.br
	  lines                 (0/1) Export linestrings for tracks and routes 
.br
	  points                (0/1) Export placemarks for tracks and routes 
.br
	  line_width            Width of lines, in pixels 
.br
	  line_color            Line color, specified in hex AABBGGRR 
.br
	  floating              (0/1) Altitudes are absolute and not clamped to ground 
.br
	  extrude               (0/1) Draw extrusion line from trackpoint to ground 
.br
	  trackdata             (0/1) Include extended data for trackpoints (default = 1 
.br
	  units                 Units used when writing comments ('s'tatute or 'm' 
.br
	  labels                (0/1) Display labels on track and routepoints  (default  
.br
	  max_position_point    Retain at most this number of position points  (0  
.br
	google                Google Maps XML
.br
	gpilots               GpilotS
.br
	  dbname                Database name 
.br
	gtm                   GPS TrackMaker
.br
	arc                   GPSBabel arc filter file
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	gpsdrive              GpsDrive Format
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	gpsdrivetrack         GpsDrive Format for Tracks
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	gpsman                GPSman
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	gpspilot              GPSPilot Tracker for Palm/OS
.br
	  dbname                Database name 
.br
	gpsutil               gpsutil
.br
	gpx                   GPX XML
.br
	  snlen                 Length of generated shortnames 
.br
	  suppresswhite         (0/1) No whitespace in generated shortnames 
.br
	  logpoint              (0/1) Create waypoints from geocache log entries 
.br
	  urlbase               Base URL for link tag in output 
.br
	  gpxver                Target GPX version for output 
.br
	hiketech              HikeTech
.br
	holux                 Holux (gm\-100) .wpo Format
.br
	hsandv                HSA Endeavour Navigator export File
.br
	html                  HTML Output
.br
	  stylesheet            Path to HTML style sheet 
.br
	  encrypt               (0/1) Encrypt hints using ROT13 
.br
	  logs                  (0/1) Include groundspeak logs if present 
.br
	  degformat             Degrees output as 'ddd', 'dmm'(default) or 'dms' 
.br
	  altunits              Units for altitude (f)eet or (m)etres 
.br
	ignrando              IGN Rando track files
.br
	  index                 Index of track to write (if more than one in source) 
.br
	ktf2                  Kartex 5 Track File
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	kwf2                  Kartex 5 Waypoint File
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	psitrex               KuDaTa PsiTrex text
.br
	lowranceusr           Lowrance USR
.br
	  ignoreicons           (0/1) Ignore event marker icons 
.br
	  merge                 (0/1) (USR output) Merge into one segmented track 
.br
	  break                 (0/1) (USR input) Break segments into separate tracks 
.br
	maggeo                Magellan Explorist Geocaching
.br
	mapsend               Magellan Mapsend
.br
	  trkver                MapSend version TRK file to generate (3,4) 
.br
	magnav                Magellan NAV Companion for Palm/OS
.br
	magellanx             Magellan SD files (as for eXplorist)
.br
	  deficon               Default icon name 
.br
	  maxcmts               Max number of comments to write (maxcmts=200) 
.br
	magellan              Magellan SD files (as for Meridian)
.br
	  deficon               Default icon name 
.br
	  maxcmts               Max number of comments to write (maxcmts=200) 
.br
	magellan              Magellan serial protocol
.br
	  deficon               Default icon name 
.br
	  maxcmts               Max number of comments to write (maxcmts=200) 
.br
	  baud                  Numeric value of bitrate (baud=4800) 
.br
	  noack                 (0/1) Suppress use of handshaking in name of speed 
.br
	  nukewpt               (0/1) Delete all waypoints 
.br
	tef                   Map&Guide 'TourExchangeFormat' XML
.br
	  routevia              (0/1) Include only via stations in route 
.br
	mag_pdb               Map&Guide to Palm/OS exported files (.pdb)
.br
	mapconverter          Mapopolis.com Mapconverter CSV
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	mxf                   MapTech Exchange Format
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	msroute               Microsoft AutoRoute 2002 (pin/route reader)
.br
	msroute               Microsoft Streets and Trips (pin/route reader)
.br
	s_and_t               Microsoft Streets and Trips 2002\-2006
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	bcr                   Motorrad Routenplaner (Map&Guide) .bcr files
.br
	  index                 Index of route to write (if more than one in source) 
.br
	  name                  New name for the route 
.br
	  radius                Radius of our big earth (default 6371000 meters) 
.br
	psp                   MS PocketStreets 2002 Pushpin
.br
	tpg                   National Geographic Topo .tpg (waypoints)
.br
	  datum                 Datum (default=NAD27) 
.br
	tpo2                  National Geographic Topo 2.x .tpo
.br
	tpo3                  National Geographic Topo 3.x/4.x .tpo
.br
	navicache             Navicache.com XML
.br
	  noretired             (0/1) Suppress retired geocaches 
.br
	nmn4                  Navigon Mobile Navigator .rte files
.br
	  index                 Index of route to write (if more than one in source) 
.br
	dna                   Navitrak DNA marker format
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	netstumbler           NetStumbler Summary File (text)
.br
	  nseicon               Non\-stealth encrypted icon name 
.br
	  nsneicon              Non\-stealth non\-encrypted icon name 
.br
	  seicon                Stealth encrypted icon name 
.br
	  sneicon               Stealth non\-encrypted icon name 
.br
	  snmac                 (0/1) Shortname is MAC address 
.br
	nima                  NIMA/GNIS Geographic Names File
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	nmea                  NMEA 0183 sentences
.br
	  snlen                 Max length of waypoint name to write 
.br
	  gprmc                 (0/1) Read/write GPRMC sentences 
.br
	  gpgga                 (0/1) Read/write GPGGA sentences 
.br
	  gpvtg                 (0/1) Read/write GPVTG sentences 
.br
	  gpgsa                 (0/1) Read/write GPGSA sentences 
.br
	  date                  Complete date\-free tracks with given date (YYYYMMDD) 
.br
	  get_posn              (0/1) Return current position as a waypoint 
.br
	  pause                 Decimal seconds to pause between groups of strings 
.br
	  baud                  Speed in bits per second of serial port (baud=4800)
.br
	ozi                   OziExplorer
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  wptfgcolor            Waypoint foreground color 
.br
	  wptbgcolor            Waypoint background color 
.br
	palmdoc               PalmDoc Output
.br
	  nosep                 (0/1) No separator lines between waypoints 
.br
	  dbname                Database name 
.br
	  encrypt               (0/1) Encrypt hints with ROT13 
.br
	  logs                  (0/1) Include groundspeak logs if present 
.br
	  bookmarks_short       (0/1) Include short name in bookmarks 
.br
	pathaway              PathAway Database for Palm/OS
.br
	  date                  Read/Write date format (i.e. DDMMYYYY) 
.br
	  dbname                Database name 
.br
	  deficon               Default icon name 
.br
	  snlen                 Length of generated shortnames 
.br
	quovadis              Quovadis
.br
	  dbname                Database name 
.br
	cup                   See You flight analysis data
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	sportsim              Sportsim track files (part of zipped .ssz files)
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	stmsdf                Suunto Trek Manager (STM) .sdf files
.br
	  index                 Index of route (if more than one in source) 
.br
	stmwpp                Suunto Trek Manager (STM) WaypointPlus files
.br
	  index                 Index of route/track to write (if more the one in  
.br
	openoffice            Tab delimited fields useful for OpenOffice, Ploticus, etc.
.br
	  snlen                 Max synthesized shortname length 
.br
	  snwhite               (0/1) Allow whitespace synth. shortnames 
.br
	  snupper               (0/1) UPPERCASE synth. shortnames 
.br
	  snunique              (0/1) Make synth. shortnames unique 
.br
	  urlbase               Basename prepended to URL on output 
.br
	  prefer_shortnames     (0/1) Use shortname instead of description 
.br
	text                  Textual Output
.br
	  nosep                 (0/1) Suppress separator lines between waypoints 
.br
	  encrypt               (0/1) Encrypt hints using ROT13 
.br
	  logs                  (0/1) Include groundspeak logs if present 
.br
	  degformat             Degrees output as 'ddd', 'dmm'(default) or 'dms' 
.br
	  altunits              Units for altitude (f)eet or (m)etres 
.br
	tomtom                TomTom POI file
.br
	tmpro                 TopoMapPro Places File
.br
	dmtlog                TrackLogs digital mapping (.trl)
.br
	  index                 Index of track (if more than one in source) 
.br
	tiger                 U.S. Census Bureau Tiger Mapping Service
.br
	  nolabels              (0/1) Suppress labels on generated pins 
.br
	  genurl                Generate file with lat/lon for centering map 
.br
	  margin                Margin for map.  Degrees or percentage 
.br
	  snlen                 Max shortname length when used with \-s 
.br
	  oldthresh             Days after which points are considered old 
.br
	  oldmarker             Marker type for old points 
.br
	  newmarker             Marker type for new points 
.br
	  suppresswhite         (0/1) Suppress whitespace in generated shortnames 
.br
	  unfoundmarker         Marker type for unfound points 
.br
	  xpixels               Width in pixels of map 
.br
	  ypixels               Height in pixels of map 
.br
	  iconismarker          (0/1) The icon description is already the marker 
.br
	unicsv                Universal csv with field structure in first line
.br
	vcard                 Vcard Output (for iPod)
.br
	  encrypt               (0/1) Encrypt hints using ROT13 
.br
	vitosmt               Vito Navigator II tracks
.br
	wfff                  WiFiFoFum 2.0 for PocketPC XML
.br
	  aicicon               Infrastructure closed icon name 
.br
	  aioicon               Infrastructure open icon name 
.br
	  ahcicon               Ad\-hoc closed icon name 
.br
	  ahoicon               Ad\-hoc open icon name 
.br
	  snmac                 (0/1) Shortname is MAC address 
.br
	wbt\-bin               Wintec WBT\-100/200 Binary file format
.br
	wbt                   Wintec WBT\-100/200 GPS Download
.br
	  erase                 (0/1) Erase device data after download 
.br
	yahoo                 Yahoo Geocode API data
.br
	  addrsep               String to separate concatenated address fields (default=", ")
.br

.br
Supported data filters:
.br
	arc                   Include Only Points Within Distance of Arc        
.br
	  file                  File containing vertices of arc (required)
.br
	  distance              Maximum distance from arc (required)
.br
	  exclude               Exclude points close to the arc 
.br
	  points                Use distance from vertices not lines 
.br
	discard               Remove unreliable points with high hdop or vdop   
.br
	  hdop                  Suppress waypoints with higher hdop 
.br
	  vdop                  Suppress waypoints with higher vdop 
.br
	  hdopandvdop           Link hdop and vdop supression with AND 
.br
	duplicate             Remove Duplicates                                 
.br
	  shortname             Suppress duplicate waypoints based on name 
.br
	  location              Suppress duplicate waypoint based on coords 
.br
	  all                   Suppress all instances of duplicates 
.br
	  correct               Use coords from duplicate points 
.br
	interpolate           Interpolate between trackpoints                   
.br
	  time                  Time interval in seconds 
.br
	  distance              Distance interval in miles or kilometers 
.br
	  route                 Interpolate routes instead 
.br
	nuketypes             Remove all waypoints, tracks, or routes           
.br
	  waypoints             Remove all waypoints from data stream 
.br
	  tracks                Remove all tracks from data stream 
.br
	  routes                Remove all routes from data stream 
.br
	polygon               Include Only Points Inside Polygon                
.br
	  file                  File containing vertices of polygon (required)
.br
	  exclude               Exclude points inside the polygon 
.br
	position              Remove Points Within Distance                     
.br
	  distance              Maximum positional distance (required)
.br
	  all                   Suppress all points close to other points 
.br
	radius                Include Only Points Within Radius                 
.br
	  lat                   Latitude for center point (D.DDDDD) (required)
.br
	  lon                   Longitude for center point (D.DDDDD) (required)
.br
	  distance              Maximum distance from center (required)
.br
	  exclude               Exclude points close to center 
.br
	  nosort                Inhibit sort by distance to center 
.br
	  maxcount              Output no more than this number of points 
.br
	  asroute               Put resulting waypoints in route of this name 
.br
	simplify              Simplify routes                                   
.br
	  count                 Maximum number of points in route 
.br
	  error                 Maximum error 
.br
	  crosstrack            Use cross\-track error (default) 
.br
	  length                Use arclength error 
.br
	sort                  Rearrange waypoints by resorting                  
.br
	  gcid                  Sort by numeric geocache ID 
.br
	  shortname             Sort by waypoint short name 
.br
	  description           Sort by waypoint description 
.br
	  time                  Sort by time 
.br
	stack                 Save and restore waypoint lists                   
.br
	  push                  Push waypoint list onto stack 
.br
	  pop                   Pop waypoint list from stack 
.br
	  swap                  Swap waypoint list with <depth> item on stack 
.br
	  copy                  (push) Copy waypoint list 
.br
	  append                (pop) Append list 
.br
	  discard               (pop) Discard top of stack 
.br
	  replace               (pop) Replace list (default) 
.br
	  depth                 (swap) Item to use (default=1) 
.br
	reverse               Reverse stops within routes                       
.br
	track                 Manipulate track lists                            
.br
	  move                  Correct trackpoint timestamps by a delta 
.br
	  pack                  Pack all tracks into one 
.br
	  split                 Split by date or time interval (see README) 
.br
	  sdistance             Split by distance 
.br
	  merge                 Merge multiple tracks for the same way 
.br
	  name                  Use only track(s) where title matches given name 
.br
	  start                 Use only track points after this timestamp 
.br
	  stop                  Use only track points before this timestamp 
.br
	  title                 Basic title for new track(s) 
.br
	  fix                   Synthesize GPS fixes (PPS, DGPS, 3D, 2D, NONE) 
.br
	  course                Synthesize course 
.br
	  speed                 Synthesize speed 
.br
	transform             Transformate waypoints into a route, tracks into routes,...
.br
	  wpt                   Transform track(s) or route(s) into waypoint(s) [R/T]
.br
	  rte                   Transform waypoint(s) or track(s) into route(s) [W/T] 
.br
	  trk                   Transform waypoint(s) or route(s) into tracks(s) [W/R]
.br


.SH SEE ALSO
Full user documentation is available at /usr/share/doc/gpsbabel/gpsbabel.html
.br
.SH AUTHORS
Major contributors:
.br
Robert Lipe Chief Babel\-Head.
.br
Ron Parker Long term contributor. Implemented route simplification, arc filter, polygon filter, TomTom, most of the Delorme formats, Palmdoc, GPSPilot, Magellan Navigator Companion, Google Maps, and the stack filter. Numerous contributions to infrastructure and many fixes.
.br
Alex Mottram Implemented the CSV subsystem, radius filter, and co\-designed the original route and track infrastructure, Topo support ##other stuff.
.br
Olaf Klein contributed support for "Motorrad Routenplaner", MapSource GDB format, Pathaway, IGN Rando, Suunto Trek Manager, Navigon Mobile Navigator, TrackFilter and character encoding transformation.
.nf

.br
